<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16887" started-at="2020-11-29T08:45:44Z" finished-at="2020-11-29T08:46:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16887" started-at="2020-11-29T08:45:44Z" finished-at="2020-11-29T08:46:01Z">
      <class name="com.learnautomation.framework.testcases.LoginTest">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@27c20538]" name="startBrowser" is-config="true" duration-ms="15501" started-at="2020-11-29T14:15:44Z" finished-at="2020-11-29T14:16:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="SKIP" signature="loginWithAdmin(java.lang.String, java.lang.String)[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@27c20538]" name="loginWithAdmin" duration-ms="0" started-at="2020-11-29T14:16:00Z" data-provider="SingleLogin" finished-at="2020-11-29T14:16:00Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Can't invoke method public java.lang.Object[][] com.learnautomation.framework.helper.DataGenerator.setLoginData() on this instance of class com.learnautomation.framework.testcases.LoginTest due to class mismatch]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] com.learnautomation.framework.helper.DataGenerator.setLoginData() on this instance of class com.learnautomation.framework.testcases.LoginTest due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:75)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithAdmin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@27c20538]" name="closeBrowser" is-config="true" duration-ms="1289" started-at="2020-11-29T14:16:00Z" finished-at="2020-11-29T14:16:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.learnautomation.framework.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
